apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: ci
servers: 1
image: rancher/k3s:v1.26.5-k3s1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --tls-san=192.168.0.196
        nodeFilters:
          - server:*
  k3d:
    wait: true
volumes:
  - volume: /etc/machine-id:/etc/machine-id
    nodeFilters:
      - server:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
kubeAPI:
  hostPort: "6443"